version: '3.9'

services:
  postgres:
    container_name: postgres_sol
    hostname: postgres
    restart: always
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: 'projel_sol'
      POSTGRES_USER: 'projel_sol'
      POSTGRES_PASSWORD: 'projel_sol'
    ports:
      - 5432:5432
    volumes:
      - sol_catalog_data:/var/lib/postgresql/data

volumes:
  sol_catalog_data:
